[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Solidity version for main contracts
solc_version = "0.8.28"

# Allow access to out-trc20 for loading bytecode
fs_permissions = [{ access = "read", path = "out-trc20" }]

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Profile for compiling legacy TRC20 USDT contracts (Solidity 0.4.x)
[profile.trc20]
src = "TRC20_USDT"
out = "out-trc20"
test = "TRC20_USDT"
script = "TRC20_USDT"
libs = []
solc_version = "0.4.26"
optimizer = true
optimizer_runs = 200
evm_version = "byzantium"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
