name: usdt_multisig
description: "USDT Multisig Wallet Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web3dart: ^2.7.3
  http: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  bs58check: ^1.0.2
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
